# db config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nutrition_assistant?serverTimezone=CET
    username: nutrition-assistant-server
    password: ENC(YCGNyvAdWueC1pn6zRydC44WDF89fkPLRittaY0TAN4=)
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  # mail config
  mail:
    host: smtp.gmail.com
    port: 587
    username: nutrition.assistant.bot
    password: ENC(pPHLu4BUzQM3tYKA5VfesPutJgHC7zIt8wqiWYyA294=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# encryptor config
jasypt:
  encryptor:
    pool-size: 4
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
    bean: jasyptEncryptor

# jwt config
jwt:
  secret: ENC(SJEowNcWOOF5NVWEFj8tdQPomJeVU1i1GXpJg25SoLC79/dbLPRQlAr+dF4SkJAM)
  expiration-time: 3600