# ==============
# Logging config
# ==============
logging:
  config: classpath:log4j2-prod.yaml

# =========
# DB config
# =========
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nutrition_assistant?serverTimezone=CET
    username: nutrition-assistant-server
    password: ENC(YCGNyvAdWueC1pn6zRydC44WDF89fkPLRittaY0TAN4=)
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  # ===========
  # Mail config
  # ===========
  mail:
    host: smtp.gmail.com
    port: 587
    username: nutrition.assistant.bot
    password: ENC(pPHLu4BUzQM3tYKA5VfesPutJgHC7zIt8wqiWYyA294=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# ================
# Encryptor config
# ================
jasypt:
  encryptor:
    pool-size: 4
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
    bean: jasyptEncryptor

# ==========
# JWT config
# ==========
jwt:
  secret: ENC(SJEowNcWOOF5NVWEFj8tdQPomJeVU1i1GXpJg25SoLC79/dbLPRQlAr+dF4SkJAM)
  expiration-time: 3600

# ======================
# USDA/FDC client config
# ======================
usda:
  fdc:
    client:
      connect-timeout: 10000  # millis
      write-timeout: 10000  # millis
      read-timeout: 10000  # millis
      api-key: ENC(C8OptM4elLnDbhUWd4cpYZZNFhfDixrhhfjkRQ0BQPntOPK+rZP8KJorOgSuyVtL6rbUlzGEoak=)

# =========================
# Nutritionix client config
# =========================
nutritionix:
  client:
    app-id: ENC(t6f9F3//Tg3spZymAWS8idDi0Gb2yev/)
    app-key: ENC(VIR8+VIIvqD7gG8VQXxvckdJXEFvqx0WwSfEAvPN02q4RqQ0u5QthR4hAhKWN78g)
    connect-timeout: 10000  # millis
    write-timeout: 10000  # millis
    read-timeout: 10000  # millis

# =================
# Scheduling config
# =================
scheduling:
  token-cleanup:
    enabled: true
    cron: 0 0/15 * * * *