nutritionix:
  client:
    app-id: ENC(t6f9F3//Tg3spZymAWS8idDi0Gb2yev/)
    api-key: ENC(VIR8+VIIvqD7gG8VQXxvckdJXEFvqx0WwSfEAvPN02q4RqQ0u5QthR4hAhKWN78g)
    connect-timeout: 10000  #millis
    write-timeout: 10000  #millis
    read-timeout: 10000  #millis