package pl.polsl.wachowski.nutritionassistant.api.error;

public enum Error {

    ENTRY_NOT_FOUND,
    UNKNOWN_NUTRIENT,
    USER_ALREADY_EXISTS,
    USER_ALREADY_ACTIVE,
    USER_INACTIVE,
    INVALID_CREDENTIALS,
    REQUEST_VALIDATION_ERROR,
    TOKEN_NOT_FOUND,
    TOKEN_EXPIRED,
    REMOTE_SERVER_ERROR,
    OTHER_ERROR

}
